### ISSUE TITLE
Roadmap for PUR ROH Project

### ISSUE THREAD

**Issue by klkeys** [asthmacollaboratory/gala2-ROH#5]
- [x] Construct a `glm` kernel `glm.pheno.onechr` to analyze a single phenotype, its covariates, and one chromosome's 0/1 SNP-in-ROH indicators. (@azeiger)
- [x] Write a function `analyze.pheno.onechr` to 
    1. take a phenotype and its covariates as arguments
    2. load one chromosome of 0/1 SNP-to-ROH indicators from a filename argument
    3. call the kernel `glm.pheno.onechr` (@azeiger)
- [x] Write a function `analyze.pheno.allchr` to analyze all chromosomes in parallel. Each chromosome is analyzed independently with its own call to `analyze.pheno.onechr`. The function will compile the results from all calls to `analyze.pheno.onechr` and produce formatted output. (@azeiger)
- [x] Write a function `plot.onepheno.results` to produce Manhattan plots and other diagnostic plots from the output of `analyze.pheno.allchr`.
- [x] Write a convenience function `load_gala_data` to load the GALA II phenotype file on Cesar.
- [x] Write a script to set up the R environment for analyzing a phenotype (load libraries, files, etc.) that uses `load_gala_data` to load data.
- [x] Analyze the BDR phenotype and compare to Zachary Szpiech's results. (@azeiger )
